### ISSUE TITLE
Granularity of cache at proxy

### ISSUE THREAD

**Issue by martinthomson** [bemasc/access-services#2]
>  Each proxy instance (as defined by its external-facing network interface) MUST share cache state among all clients to ensure that they use the same Access Descriptions for each Oblivious Request Resource.

I believe that the right answer is that all oblivious proxy resources at the same server need to share a cache as long as the oblivious request resource is the same.  The external-facing network interface doesn't seem right.  I get that there are proxies that won't want to share state across multiple worker instances, but that might be dealt with using an exception.

**Comment by bemasc** [comment]
OK, I've adjusted the language here to be less specific and focus on the objective, rather than the mechanism.
