### ISSUE TITLE
no-cache requests

### ISSUE THREAD

**Issue by martinthomson** [bemasc/access-services#6]
Regarding the deanonymization attack in Section 7.1.2, RFC 8246 says:

> [...] proxies SHOULD skip conditionally revalidating fresh responses containing the immutable extension unless there is a signal from the client that a validation is necessary (e.g., a no-cache Cache-Control request directive [...]

This suggests that the refresh of state is possible if the proxy acts as a typical HTTP intermediary.  Special rules might be needed.

**Comment by bemasc** [comment]
Good point!  I've added a reference to that text and expanded the text about not revalidating.
